Bump fl-clash to 0.8.97
```
3 installed gems you directly depend on are looking for funding.
  Run `bundle fund` for details
==> Downloading https://github.com/chen08209/FlClash/releases/download/v0.8.97/FlClash-0.8.97-macos-amd64.dmg
==> Downloading from https://release-assets.githubusercontent.com/github-production-release-asset/678716433/240bce66-68ee-4d83-b0dc-916c01559495?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-09-10T07%3A32%3A21Z&rscd=attachment%3B+filename%3DFlClash-0.8.97-macos-amd64.dmg&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-09-10T06%3A31%3A51Z&ske=2026-09-10T07%3A32%3A21Z&sks=b&skv=2018-11-09&sig=C2Jv9tyfTdXvLHbmirPTffYBtRQHfNYJNhKfLwXmnMY%3D&jwt=***
==> Downloading https://github.com/chen08209/FlClash/releases/download/v0.8.97/FlClash-0.8.97-macos-arm64.dmg
==> Downloading from https://release-assets.githubusercontent.com/github-production-release-asset/678716433/df1c5d6e-fcba-4e48-981f-d61c9797580f?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-09-10T07%3A34%3A40Z&rscd=attachment%3B+filename%3DFlClash-0.8.97-macos-arm64.dmg&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-09-10T06%3A34%3A20Z&ske=2026-09-10T07%3A34%3A40Z&sks=b&skv=2018-11-09&sig=TdF5p7EZFR6gNUkeWancDr%2Bvvmik5pJ3Si4P0GwY2OU%3D&jwt=***
==> Downloading and extracting artifacts
==> Downloading https://github.com/chen08209/FlClash/releases/download/v0.8.97/FlClash-0.8.97-macos-arm64.dmg
Already downloaded: /Users/runner/Library/Caches/Homebrew/downloads/4bac79c23bc0befb823603a58bf17f1536f8daca16b17c87fe1349aa21c1ca22--FlClash-0.8.97-macos-arm64.dmg
==> Downloading https://github.com/chen08209/FlClash/releases/download/v0.8.97/FlClash-0.8.97-macos-arm64.dmg
Already downloaded: /Users/runner/Library/Caches/Homebrew/downloads/4bac79c23bc0befb823603a58bf17f1536f8daca16b17c87fe1349aa21c1ca22--FlClash-0.8.97-macos-arm64.dmg
audit for fl-clash: failed
 - Artifact defined :monterey as the minimum macOS version but the cask declared no minimum macOS version
goooler/repo/fl-clash
  * Artifact defined :monterey as the minimum macOS version but the cask declared no minimum macOS version
Error: 1 problem in 1 cask detected.
Error: Artifact defined :monterey as the minimum macOS version but the cask declared no minimum macOS version
Error: `brew audit` failed!
```