Must run auto-bump on macos-latest
Fixes

```
Taps/goooler/homebrew-repo/Casks/clash-mac.rb:23:3: C: [Corrected] Cask/StanzaOrder: postflight stanza out of order
  postflight do ...
  ^^^^^^^^^^^^^
Taps/goooler/homebrew-repo/Casks/clash-mac.rb:28:20: C: [Corrected] Style/StringLiterals: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
    system_command '/usr/bin/xattr', args: ['-cr', "#{appdir}/ClashMac.app"], sudo: false
                   ^^^^^^^^^^^^^^^^
Taps/goooler/homebrew-repo/Casks/clash-mac.rb:28:45: C: [Corrected] Style/StringLiterals: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
    system_command '/usr/bin/xattr', args: ['-cr', "#{appdir}/ClashMac.app"], sudo: false
                                            ^^^^^
Taps/goooler/homebrew-repo/Casks/clash-mac.rb:31:3: C: [Corrected] Cask/StanzaOrder: depends_on stanza out of order
  depends_on macos: ">= :big_sur"
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

1 file inspected, 4 offenses detected, 4 offenses corrected
Switched to a new branch 'bump-clash-mac-1.1.23'
M	Casks/clash-mac.rb
Author identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: empty ident name (for <runner@runnervmh13bl.3xvpnnmqe0pufide3cozgi5fjc.cx.internal.cloudapp.net>) not allowed
Error: Failure while executing; `git commit --no-edit --verbose --message=clash-mac\ 1.1.23 -- /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/goooler/homebrew-repo/Casks/clash-mac.rb` exited with 128.
```